name: Build Deimos Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'dev-main'
        type: string
  schedule:
    # Run once per week on Sunday at 6 AM UTC
    - cron: '0 6 * * 0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        # For scheduled runs, build from main branch
        # For manual runs, use the specified branch
        # For push/PR, use the default behavior
        ref: ${{ github.event.inputs.branch || (github.event_name == 'schedule' && 'main') || github.ref }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Specify your Python version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --force-reinstall
        pip install pyinstaller
      continue-on-error: false
    
    - name: Build with PyInstaller
      run: |
        pyinstaller -F -w --clean -i Deimos-logo.ico --version-file version_info.txt Deimos.py --noupx --optimize 2 --manifest "app.manifest"
    
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: Deimos-${{ github.event.inputs.branch || github.ref_name }}-${{ github.run_number }}
        path: dist/Deimos.exe
        retention-days: 7  # Keep the artifact for 7 days
